language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - export BOTO_CONFIG=/dev/null
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -r requirements.txt

script:
  - cd tests; python -m pytest
