embeddings:
    glove:
        path: <++FILL ME IN++>
        oov_token: "."  # wild guess
        lowercase: <++True++>


    word2vec:
        path: "/data3/lgalke/GoogleNews-vectors-negative300.bin.gz"
        oov_token: "UNK"  # not so wild guess
        lowercase: False


data:
    econ62k:
        type: "QuadflorLike"
        X: "/data3/kd-mp/kd-mp/Resources/Goldstandard/formatted_econbiz-annotation-62k-titles.csv"
        Y: "/data3/kd-mp/kd-mp/Resources/Goldstandard/econbiz-stw9-formatted.csv"
        thes: "/data3/kd-mp/kd-mp/Resources/Ontologies/stw.json" 
        verbose: 1

    econfull:
        type: "QuadflorLike"
        X: "/data3/kd-mp/data/ZBW62k/Text"
        Y: "/data3/kd-mp/kd-mp/Resources/Goldstandard/econbiz-stw9-formatted.csv"
        thes: "/data3/kd-mp/kd-mp/Resources/Ontologies/stw.json" 

    ntcir2:
        type: "ntcir"
        base-path: "../data/NTCIR2/"
        field: "title"
        topic: "title"
        rels: 2
            
