verify_integrity: False
lowercase: True
embedding: "/data3/lgalke/GoogleNews-vectors-negative300.bin.gz"

econ62k:
    use_fulltext: False
    fulltext_path: "/data3/kd-mp/data/ZBW62k/Text"
    title_path: "/data3/kd-mp/kd-mp/Resources/Goldstandard/formatted_econbiz-annotation-62k-titles.csv"
    gold_path: "/data3/kd-mp/kd-mp/Resources/Goldstandard/econbiz-stw9-formatted.csv"
    thesaurus_path: "/data3/kd-mp/kd-mp/Resources/Ontologies/stw.json" 
    verbose: 1

ntcir2:
    base-path: "../data/NTCIR2/"
    field: "title"
    topic: "title"
    rels: 2
        
