embeddings:
    glove:
        path: "/data3/lgalke/glove.gnsm"
        oov_token: "UNK"  # wild guess
        analyzer:
            lowercase: False
            tokenizer: "nltk"
            stop_words: False


    word2vec:
        path: "/data3/lgalke/GoogleNews-vectors-negative300.bin.gz"
        oov_token: "UNK"  # not so wild guess
        analyzer:
            lowercase: False
            tokenizer: "sword"
            stop_words: True

data:
    econ62k:
        type: "QuadflorLike"
        X: "/data3/kd-mp/kd-mp/Resources/Goldstandard/formatted_econbiz-annotation-62k-titles.csv"
        y: "/data3/kd-mp/kd-mp/Resources/Goldstandard/econbiz-stw9-formatted.csv"
        thes: "/data3/kd-mp/kd-mp/Resources/Ontologies/stw.json" 

    econfull:
        type: "QuadflorLike"
        X: "/data3/kd-mp/data/ZBW62k/Text"
        y: "/data3/kd-mp/kd-mp/Resources/Goldstandard/econbiz-stw9-formatted.csv"
        thes: "/data3/kd-mp/kd-mp/Resources/Ontologies/stw.json" 

    ntcir2:
        type: "ntcir"
        root_path: "../data/NTCIR2/"
        field: "title"
        topic: "title"
        rels: 2

    ntcir2abstract:
        type: "ntcir"
        root_path: "../data/NTCIR2/"
        field: "content"
        topic: "title"
        rels: 2
            
